// Run from repo root with Playwright installed. GG_CHROMIUM_PATH is optional.
const fs=require('fs'),http=require('http'),path=require('path'),assert=require('node:assert/strict');const {chromium}=require('playwright');
(async()=>{
 const root=path.resolve(__dirname,'..');const server=http.createServer((req,res)=>{const p=path.join(root,decodeURIComponent(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));try{const data=fs.readFileSync(p);res.setHeader('Content-Type',p.endsWith('.js')?'application/javascript':p.endsWith('.json')?'application/json':p.endsWith('.css')?'text/css':'text/html');res.end(data);}catch{res.statusCode=404;res.end('Missing');}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const base='http://127.0.0.1:'+server.address().port;const b=await chromium.launch({headless:true,executablePath:process.env.GG_CHROMIUM_PATH||undefined,args:['--no-sandbox'],env:{...process.env,LD_LIBRARY_PATH:process.env.GG_CHROMIUM_LIBS||process.env.LD_LIBRARY_PATH||''}});
 let state=null,revision=0,failWrite=false;const uploads=new Set(),errors=[];let context;
 try{
 context=await b.newContext({permissions:['clipboard-read','clipboard-write']});
 await context.route('https://fonts.googleapis.com/**',r=>r.abort());await context.route('https://fonts.gstatic.com/**',r=>r.abort());
 await context.route('https://*.supabase.co/**',async route=>{const req=route.request(),u=new URL(req.url());if(u.pathname.startsWith('/rest/v1/gg_hub_state'))return route.fulfill({json:state?[{payload:state,revision}]:[]});if(u.pathname.endsWith('/rpc/gg_hub_save')){const data=req.postDataJSON();if(failWrite){failWrite=false;return route.fulfill({status:500,json:{message:'test outage'}});}if(data.expected_revision!==revision)return route.fulfill({status:409,json:{message:'GG_CONFLICT'}});state=data.new_payload;revision++;return route.fulfill({json:revision});}if(u.pathname.startsWith('/storage/v1/object/')){if(req.method()==='POST')uploads.add(u.pathname);return route.fulfill({json:{Key:u.pathname}});}return route.fulfill({status:404,json:{}});});
 const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());await p.goto(base);await p.getByText('Shared content connected').waitFor();assert.equal(await p.locator('.grid .card').count(),6);assert.match(await p.locator('.grid .card').nth(4).innerText(),/HOLIDAY LIGHTING/);
 await p.getByRole('button',{name:'+ Add card',exact:true}).click();await p.getByLabel('Card title').fill('TEST BOARD');await p.getByRole('button',{name:'Save',exact:true}).click();await p.getByText('TEST BOARD',{exact:true}).waitFor();assert.equal(state.cards.length,7);
 await p.goto(base+'/mastercomms.html');await p.getByText('Shared content connected').waitFor();assert.equal(await p.locator('.gg-item').count(),12);
 await p.getByRole('button',{name:'+ Add entry',exact:true}).click();await p.getByLabel('Title',{exact:true}).fill('Test inquiry');await p.getByLabel('Message / script / notes').fill('Hello <script>alert(1)</script> client.');await p.getByRole('button',{name:'Save',exact:true}).click();await p.getByText('Test inquiry',{exact:true}).waitFor();let item=state.items.find(x=>x.title==='Test inquiry');assert.ok(item);
 let card=p.locator(`[data-item="${item.id}"]`);await card.locator('summary').click();assert.match(await card.innerText(),/<script>/);await card.getByRole('button',{name:'Copy message',exact:true}).click();assert.match(await p.evaluate(()=>navigator.clipboard.readText()),/Hello <script>/);
 await card.getByRole('button',{name:'Edit',exact:true}).click();await p.getByLabel('Title',{exact:true}).fill('Updated inquiry');failWrite=true;await p.getByRole('button',{name:'Save',exact:true}).click();await p.locator('.gg-error').filter({hasText:'Nothing was saved'}).waitFor();assert.equal(state.items.find(x=>x.id===item.id).title,'Test inquiry');await p.getByRole('button',{name:'Save',exact:true}).click();await p.getByText('Updated inquiry',{exact:true}).waitFor();
 await p.getByRole('button',{name:'+ Add tab',exact:true}).click();await p.getByLabel('Tab name').fill('New category');await p.getByRole('button',{name:'Save',exact:true}).click();await p.getByRole('button',{name:'New category',exact:true}).click();await p.getByRole('button',{name:'Delete tab',exact:true}).click();assert.ok(!state.categories.some(x=>x.title==='New category'));
 await p.getByRole('button',{name:'🎄 Holiday Lighting',exact:true}).click();await p.getByRole('button',{name:'+ Add entry',exact:true}).click();await p.getByLabel('Title',{exact:true}).fill('Shared holiday entry');await p.getByLabel('Message / script / notes').fill('Shared between both boards.');await p.getByRole('button',{name:'Save',exact:true}).click();
 const p2=await context.newPage();p2.on('pageerror',e=>errors.push(e.message));p2.on('dialog',d=>d.accept());await p2.goto(base+'/holiday.html');await p2.getByText('Shared content connected').waitFor();await p2.getByRole('button',{name:'Emails',exact:true}).click();await p2.getByText('Shared holiday entry',{exact:true}).waitFor();
 const holidayItem=state.items.find(x=>x.title==='Shared holiday entry');await p2.locator(`[data-item="${holidayItem.id}"] summary`).click();await p2.locator(`[data-item="${holidayItem.id}"]`).getByRole('button',{name:'Edit',exact:true}).click();await p2.getByLabel('Message / script / notes').fill('Draft survives conflict');revision++;await p2.getByRole('button',{name:'Save',exact:true}).click();await p2.locator('.gg-error').filter({hasText:'Someone else saved'}).waitFor();assert.equal(await p2.getByLabel('Message / script / notes').inputValue(),'Draft survives conflict');await p2.getByRole('button',{name:'Save',exact:true}).click();
 await p2.getByRole('button',{name:'Booklets & Files',exact:true}).click();await p2.getByRole('button',{name:'+ Add file / PDF',exact:true}).click();await p2.getByLabel('Title',{exact:true}).fill('Test PDF');await p2.locator('input[type=file]').setInputFiles({name:'test.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\n%%EOF')});await p2.getByRole('button',{name:'Save',exact:true}).click();await p2.getByText('Test PDF',{exact:true}).waitFor();assert.equal(uploads.size,1);
 const pdf=state.items.find(x=>x.title==='Test PDF'),oldUrl=pdf.url;
 await p2.getByRole('button',{name:'Emails',exact:true}).click();let shared=p2.locator(`[data-item="${holidayItem.id}"]`);await shared.locator('summary').click();await shared.getByRole('button',{name:'Edit',exact:true}).click();await p2.getByLabel('Test PDF',{exact:true}).check();await p2.getByRole('button',{name:'Save',exact:true}).click();
 await p2.getByRole('button',{name:'Booklets & Files',exact:true}).click();let pdfCard=p2.locator(`[data-item="${pdf.id}"]`);await pdfCard.locator('summary').click();await pdfCard.getByRole('button',{name:'Edit',exact:true}).click();await p2.locator('input[type=file]').setInputFiles({name:'replacement.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\n%%EOF')});await p2.getByRole('button',{name:'Save',exact:true}).click();await p2.waitForFunction(({id,url})=>GGStore.data.items.find(x=>x.id===id)?.url!==url,{id:pdf.id,url:oldUrl});assert.notEqual(state.items.find(x=>x.id===pdf.id).url,oldUrl);
 await p2.getByRole('button',{name:'Emails',exact:true}).click();shared=p2.locator(`[data-item="${holidayItem.id}"]`);await shared.locator('summary').click();assert.equal(await shared.getByRole('link',{name:'Test PDF',exact:true}).getAttribute('href'),state.items.find(x=>x.id===pdf.id).url);
 await p2.getByRole('button',{name:'Booklets & Files',exact:true}).click();pdfCard=p2.locator(`[data-item="${pdf.id}"]`);await pdfCard.locator('summary').click();await pdfCard.getByRole('button',{name:'Delete',exact:true}).click();await p2.waitForFunction(id=>!GGStore.data.items.some(x=>x.id===id),pdf.id);assert.ok(!state.items.find(x=>x.id===holidayItem.id).attachments.includes(pdf.id));

 await p.goto(base+'/gg_calculators.html');await p.getByText('Shared content connected').waitFor();await p.getByRole('button',{name:'🛡️ Install Costs',exact:true}).click();assert.equal(await p.locator('#gm-cost').inputValue(),'');await p.locator('#gm-ft').fill('180');await p.locator('#gm-rate').fill('10');assert.ok(await p.locator('#gm-copy').isDisabled());await p.locator('#gm-cost').fill('20');assert.equal(await p.locator('#gm-sections').innerText(),'25');assert.equal(await p.locator('#gm-guard-cost').innerText(),'$565.00');assert.match(await p.locator('#gm-quote').innerText(),/2,?672.45/);await p.locator('#gm-unit-0').fill('16.09');await p.locator('#gm-qty-0').fill('1');assert.match(await p.locator('#gm-spout-total').innerText(),/18.18/);await p.locator('#gm-rate').fill('13');assert.match(await p.locator('#gm-validation').innerText(),/13.00/);
 await p.getByRole('button',{name:'🎄 Holiday Lighting',exact:true}).click();await p.locator('#light-ft').fill('100');await p.locator('#light-rate').fill('10');assert.match(await p.locator('#light-results').innerText(),/1130.00/);
 await p.getByRole('button',{name:'📍 Address Lookup',exact:true}).click();await p.getByLabel('Property address').fill('123 Test Street, Pickering, Ontario');await p.evaluate(()=>{window.open=(u)=>{window.testMapsUrl=u;};});await p.getByRole('button',{name:'Open Google Maps',exact:true}).click();assert.match(await p.evaluate(()=>window.testMapsUrl),/query=123%20Test/);
 await p.goto(base+'/GG_PICaso.html');await p.getByText('Shared content connected').waitFor();await p.getByRole('button',{name:'SERVICE RESULTS',exact:true}).click();await p.evaluate(()=>{window.drawnText=[];const fn=CanvasRenderingContext2D.prototype.fillText;CanvasRenderingContext2D.prototype.fillText=function(t,...a){window.drawnText.push(t);return fn.call(this,t,...a);};});await p.locator('input[type=file]').setInputFiles({name:'pixel.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j4XcAAAAASUVORK5CYII=','base64')});await p.locator('#gen-btn').click();await p.waitForFunction(()=>document.getElementById('result-img').src.startsWith('data:image/jpeg'));assert.ok((await p.evaluate(()=>window.drawnText)).includes('SERVICE RESULTS'));
 await p.setViewportSize({width:390,height:844});await p.goto(base+'/holiday.html');await p.getByText('Shared content connected').waitFor();assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:'/tmp/gg-holiday-mobile.png',fullPage:true});
 await p.setViewportSize({width:1440,height:1000});await p.goto(base);await p.getByText('Shared content connected').waitFor();await p.waitForFunction(()=>getComputedStyle(document.querySelector('.logo')).opacity==='1'&&getComputedStyle(document.querySelector('.grid .card')).opacity==='1');await p.screenshot({path:'/tmp/gg-home.png',fullPage:true});
 assert.deepEqual(errors,[]);console.log('Browser checks passed: shared editing, navigation, copy, safe text, save failure, conflict handling, upload, calculators, Maps, Service Results, mobile layout.');
 }finally{await b.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
